# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
fr:
  langaugeCode: fr-fr
  contentDir: content/fr

en:
  languageCode: en-us
  contentDir: content/en
  title: Mapper.fr
  params:
    description: Personal website of Jérémy Garniaux, geographer, mapmaker & developer.
  menu:
    main:
    - name: About
      url: '#about'
      weight: 10
    - name: Resume
      url: '#resume'
      weight: 20
    - name: Blog
      url: '#blog'
      weight: 30
    - name: Contact
      url: '#contact'
      weight: 40
